### ISSUE TITLE
No pioneers as expansion

### ISSUE THREAD

**Issue by ViezeVingertjes** [kasami/kasamibot#5]
It tries to expand and grow to level 3(?) with only a few ExpansionWorkers, but it should just do it like in the first room, with pioneers imo. It can be forced by setting the expansion property to false but it would be much better if it was default behavior.

**Comment by kasami** [comment]
When the room sending out expansionworkers has a high RCL, it is usually beneficial to use ExpansionWorkers up to RCL 3 (where it should start spawning its own units). However, from expansions from lower RCL-rooms (like when one has a lot of GCL to expand), it might cause problems.

I'm planning to merge togehter the Pioneer and ExpansionWorker, since they have a lot of common code, and similar jobs, so that should at least partially fix this.
